# Generated by Django 4.2.2 on 2023-06-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='drawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='measured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='numbered',
            field=models.BooleanField(default=False),
        ),
    ]
