# Generated by Django 4.2.2 on 2023-07-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='invent_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
