# Generated by Django 4.2.2 on 2023-08-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0004_subject_address_subject_invent_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('BU', 'Багатоповерхівка'), ('CO', 'Будівля'), ('GA', 'Гараж'), ('HO', 'Особняк'), ('AP', 'Квартира'), ('KE', 'КЕВ'), ('QU', 'Нежитлове приміщення'), ('UF', 'Незавершене'), ('SH', 'Садовий будинок')], default='HO', max_length=2),
        ),
    ]
