# Generated by Django 4.2.2 on 2023-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0006_subject_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='priority',
            field=models.CharField(choices=[('1HI', 'Високий'), ('2NO', 'Звичайний'), ('3LO', 'Низький')], default='2NO', max_length=3),
        ),
    ]
