# Generated by Django 4.2.2 on 2023-08-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0007_alter_subject_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='priority',
            field=models.CharField(choices=[('AA', 'Високий'), ('BB', 'Звичайний'), ('CC', 'Низький')], default='BB', max_length=3),
        ),
    ]
