# Generated by Django 4.2.2 on 2023-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0008_subject_archived_alter_subject_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='typed',
            field=models.BooleanField(default=False),
        ),
    ]
