# Generated by Django 4.2.2 on 2023-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0011_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='client_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
