# Generated by Django 4.2 on 2024-04-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0016_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
