# Generated by Django 4.2 on 2024-04-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0017_rename_contacts_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='contact_number',
        ),
    ]
