# Generated by Django 4.2 on 2024-05-10 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bord', '0018_rename_name_contact_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
